version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /mnt/docker/jellyfin:/config
      - /mnt/tv:/data/tvshows
      - /mnt/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
      #devices:
      #- /dev/dri:/dev/dri
      #- /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
networks: {}
